
[general]
	#Whether crops are affected by seasons.
	seasonal_crops = true
	#Whether unlisted seeds are fertile every season. False means they're fertile every season except Winter
	ignore_unlisted_crops = false
	#How crops behave when out of season.
	#0 = Grow slowly
	#1 = Can't grow
	#2 = Break when trying to grow
	#Range: 0 ~ 2
	out_of_season_crop_behavior = 1
	#Maximum underground Y level out of season crops can be grown below.  Set to -1 to disable feature
	#Range: > -1
	underground_fertility_level = 40
	#Whether to include tooltips on crops listing which seasons they're fertile in. Note: This only applies to listed crops.
	crop_tooltips = false

[seasonal_fertility]
	#Crops growable in Spring
	#(List either the seed item for the crop, or the crop block itself)
	spring_crops = ["minecraft:oak_sapling", "minecraft:birch_sapling", "minecraft:spruce_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:red_mushroom", "minecraft:brown_mushroom", "minecraft:nether_wart", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:twisting_vines", "minecraft:twisting_vines_plant", "minecraft:weeping_vines", "minecraft:weeping_vines_plant", "minecraft:seagrass", "minecraft:sea_pickle"]
	#Crops growable in Winter
	#(List either the seed item for the crop, or the crop block itself)
	winter_crops = ["minecraft:oak_sapling", "minecraft:birch_sapling", "minecraft:spruce_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:red_mushroom", "minecraft:brown_mushroom", "minecraft:nether_wart", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:twisting_vines", "minecraft:twisting_vines_plant", "minecraft:weeping_vines", "minecraft:weeping_vines_plant", "minecraft:seagrass", "minecraft:sea_pickle"]
	#Crops growable in Summer
	#(List either the seed item for the crop, or the crop block itself)
	summer_crops = ["minecraft:oak_sapling", "minecraft:birch_sapling", "minecraft:spruce_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:red_mushroom", "minecraft:brown_mushroom", "minecraft:nether_wart", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:twisting_vines", "minecraft:twisting_vines_plant", "minecraft:weeping_vines", "minecraft:weeping_vines_plant", "minecraft:seagrass", "minecraft:sea_pickle"]
	#Crops growable in Autumn
	#(List either the seed item for the crop, or the crop block itself)
	autumn_crops = ["minecraft:oak_sapling", "minecraft:birch_sapling", "minecraft:spruce_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:red_mushroom", "minecraft:brown_mushroom", "minecraft:nether_wart", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:twisting_vines", "minecraft:twisting_vines_plant", "minecraft:weeping_vines", "minecraft:weeping_vines_plant", "minecraft:seagrass", "minecraft:sea_pickle"]

