#How dense the fog effect during a snowstorm is.
#Range: 0.0 ~ 1.0
fogDensity = 0.105
#How visually dense the snow weather effect is. Normally, vanilla sets this to 5 with fast graphics, and 10 with fancy graphics.
#Range: 1 ~ 15
snowDensity = 10
#Enable snow (actually rain) weather sounds.
snowSounds = true
#Enable wind / snow storm weather sounds.
windSounds = true
#This is the fog color during the day. This is a hex color code, with 8 bits each for red, green, blue.
#Range: 0 ~ 16777215
fogColorDay = 12566488
#This is the fog color during the night. This is a hex color code, with 8 bits each for red, green, blue.
#Range: 0 ~ 16777215
fogColorNight = 789529
#Changes the weather renderer to one which renders faster, denser snow. Note: this requires a world reload to take effect.
weatherRenderChanges = true
#Changes the sky renderer to one which does not render sunrise or sunset effects during a snowstorm. Note: this requires a world reload to take effect.
skyRenderChanges = true

