#Should the vanilla /weather be disabled? Any changes require a world restart to take effect.
disableWeatherCommand = true
#A list of biome IDs that will not be forcibly converted to frozen wastelands. Any changes requires a MC restart to take effect.
nonWinterBiomes = ["minecraft:nether_wastes", "minecraft:crimson_forest", "minecraft:warped_forest", "minecraft:basalt_deltas", "minecraft:soul_sand_valley", "minecraft:the_void"]

