
["Spawn Biome Utility Control Values"]
	#maximum Spawn Weight
	#Range: 1 ~ 1000
	maxSpawnWeight = 120
	#suppressMinecraftMobReporting
	suppressMinecraftMobReporting = false
	#Fix min, max values and add nether creatures
	fixSpawnValues = true
	#fixEmptyNether
	fixEmptyNether = false
	#minimum Spawn Weight
	#Range: 1 ~ 1000
	minSpawnWeight = 5
	#generateReport
	generateReport = false
	#Mod Name set separated by SemiColons of mods to report.
	includedReportModsSet = ";"
	#Use the BiomeMobWeight.CSV file to balance Biome spawn values
	balanceBiomeSpawnValues = true
	#Use the StructMobWeight.CSV file to balance structure spawn values
	balanceStructureSpawnValues = true
	#Debug Level: 0 = Off, 1 = Log, 2 = Chat+Log
	#Range: 0 ~ 2
	debugLevel = 1

