
[gui]
	#Displays info on top of Structure Blocks, similarly to pre-1.13 versions.
	show_structure_block_info = true
	#Skips the screen that tells you that a world uses experimental settings.
	skip_experimental_backup_screen = true

[entity]
	#Fixes spawners causing fps lag from a ClassCastException with some entities.
	fix_spawners = true

